from pydantic import BaseModel, Field


class DSATestCase(BaseModel):
    input: str = Field(
        description="Complete stdin input for one test case"
    )

    explanation: str = Field(
        description="Why this test case is useful for testing the solution"
    )

    expected_output: str | None = Field(
        default=None,
        description="Expected stdout generated by the verified reference solution"
    )

    is_hidden: bool = True

# from pydantic import BaseModel, Field


# class DSATestCase(BaseModel):
#     input: str = Field(
#         description="Complete stdin input for one test case"
#     )

#     expected_output: str = Field(
#         description="Expected stdout output for the test case"
#     )

#     explanation: str = Field(
#         description="Why this test case is useful for testing the solution"
#     )

#     is_hidden: bool = True